---
langs: [fr_FR,en_US,es_ES]
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
plugins:
- jekyll-seo-tag
title: "Documentation Plugin SNMP"
description: "Ceci est la documentation du plugin SNMP"
author: "Jeedom-Plugins-Extra"
image: https://avatars1.githubusercontent.com/u/36200380?s=200&v=4
social:
  name: Jeedom-Plugins-Extra
  links:
    - https://github.com/Jeedom-Plugins-Extra/plugin-SNMP
